name: Build nav
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install
      uses: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true
    - name: Build
      run: |
        npm run build
    - name: Deploy
      run: |
        git config --global user.name 'peng'
        git config --global user.email '893774743@qq.com'
        cd dist/
        git add -A
        git commit -m 'create to gh-pages'
        git push origin gh-pages -f
        
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: dist
